//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comments
    {
        [Key]
        public System.Guid CommentId { get; set; }
        public System.Guid ProfileId { get; set; }
        public System.DateTime creationTime { get; set; }
        public string text { get; set; }
        public System.Guid TargetId { get; set; }
    }
}
