//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Messages
    {
        [Key]

        public System.Guid MessageId { get; set; }
        public System.Guid from { get; set; }
        public System.Guid to { get; set; }
        public System.DateTime creationTime { get; set; }
        public string text { get; set; }
        public Nullable<System.Guid> TalkId { get; set; }
    
        public virtual Profiles Profiles { get; set; }
        public virtual Profiles Profiles1 { get; set; }
    }
}
